- .github/workflows/lint.yml
- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- LICENSE
- README.md
- benches/bit_math.rs
- benches/sqrt_price_math.rs
- benches/swap_math.rs
- benches/tick_math.rs
- src/lib.rs
- src/utils/tick_list.rs
This commit updates the project identity from 'uniswap-v3-sdk-rs' to 'uniswap-v3-sdk'. It includes enhancing package information by providing a new description, author details, and inserting the MIT license. Also, the codebase has been updated in various places to reflect this change in identity. GitHub workflow names has been simplified too. The 'cargo clippy' and 'cargo fmt' commands were updated for thorough checking.
> Enhance package info

- Cargo.lock
- Cargo.toml
- src/utils/encode_sqrt_ratio_x96.rs
- src/utils/max_liquidity_for_amounts.rs
- src/utils/mod.rs
- src/utils/price_tick_conversions.rs
This commit adds a new utility to compute the maximum amount of liquidity received for given amounts of two tokens. It provides two variants of computation, one precise and another imprecise, to accommodate both precise and fast computational needs. This utility will help in calculating how much liquidity will be received for given amounts of tokens at certain price boundaries. Tests are also added to verify the functionality of this module.
> Add utility to compute maximum liquidity for given amounts

- Cargo.lock
- Cargo.toml
- src/entities/position.rs
Corrected the order of `sqrt_ratio_x96_upper` and `sqrt_ratio_x96_lower` in both `mint_amounts_with_slippage` and `burn_amounts_with_slippage` methods in `position.rs`. Added a variety of tests to ensure these methods function as expected under different conditions, including min/max pool price and different position scenarios.
> Fix incorrect variable ordering and test `position.rs`

- Cargo.lock
- Cargo.toml
- README.md
- src/extensions/ephemeral_tick_data_provider.rs
- src/extensions/mod.rs
- src/extensions/price_tick_conversions.rs
- src/utils/price_tick_conversions.rs
This update introduces utility functions for conversions between ticks, prices, and SDK Core prices. Additionally, it provides methods to parse a price string into a `Price` instance, transform a sqrt ratio to a `Price` object, convert a tick to a `BigDecimal` price, and change a `FractionBase` to a `BigDecimal`. Code has been refactored where necessary, and package versions have been updated, including upgrading uniswap-v3-sdk to 0.11.0. Tests for the new utilities need to be written.
> Extend price and tick conversion utilities

- Cargo.lock
- Cargo.toml
- src/entities/pool.rs
- src/extensions/mod.rs
- src/extensions/pool.rs
This commit adds a method for obtaining the pool address to the pool entity and further extends the pool utilities in the extensions module. In addition to this, module behavior is further demonstrated through added tests. The uniswap-v3-sdk package version is also updated to 0.12.0.
> Add `address` method to pool entity and extend pool utilities

- Cargo.lock
- Cargo.toml
- benches/bit_math.rs
- benches/sqrt_price_math.rs
- benches/swap_math.rs
- benches/tick_math.rs
- src/extensions/ephemeral_tick_data_provider.rs
- src/extensions/pool.rs
- src/extensions/position.rs
- src/utils/mod.rs
- src/utils/sqrt_price_math.rs
- src/utils/types.rs
This commit introduces a new `types` module which is used to convert between ethers types and alloy types. This provides a more streamlined conversion mechanism and reduces dependencies on individual methods for conversion. This implementation involves changes throughout various parts of the codebase including sqrt price math, bit math, pool, and others. It also includes the addition of ethers-core as a dependency in Cargo.toml.
> Update data conversions with newly added `types` module

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/multicall.rs
A new module `multicall` has been added to provide multicall functionality within the `uniswap-v3-sdk`. This includes the creation of a new `multicall` solidity function and an `encode_multicall` function for encoding the input data. Associated tests for these functions have been included as well. Also, the package version has been updated from 0.14.0 to 0.15.0.
> Add multicall functionality

- Cargo.lock
- Cargo.toml
- README.md
- src/entities/mod.rs
- src/entities/route.rs
This commit adds a new entity called Route which represents a list of pools through which a swap can occur, with associated constructor and methods. Along with this, the code also includes test cases for the new entity. Additionally, the version of the package has also been bumped up along with various dependency upgrades including tokio and toml_edit.
> Add `Route` entity and upgrade dependencies

- Cargo.toml
- src/entities/pool.rs
- src/entities/route.rs
- src/entities/trade.rs
- src/extensions/price_tick_conversions.rs
- src/nonfungible_position_manager.rs
- src/swap_router.rs
- src/utils/mod.rs
- src/utils/price_tick_conversions.rs
This commit refines the uniswap-v3-sdk's source code by replacing occurrences of '.meta.currency' with '.currency'. The change covers several .rs files, from 'swap_router.rs' to 'nonfungible_position_manager.rs', effectively streamlining the code for improved clarity and readability. The 'uniswap-sdk-core' version is also updated from 0.15.0 to 0.16.0.
> chore(refactor): Refactor code to replace `meta.currency` with `currency`

- Cargo.toml
- src/entities/trade.rs
This update refactors the code in trade.rs to directly handle mutable vectors without wrapping them in RefCell. Some iterative operations are also optimized for better readability and performance. Additionally, this update involves an upgrade to the uniswap-sdk-core from version 0.18 to 0.20.0.
> refactor(trade): Use `&mut` instead of `RefCell` for best trade

- src/utils/bit_math.rs
The EVM only exposes to simple operations so libraries must resort to black magic to make more complex operations work and be performant. This doesn't map to the real world well, where we can simply use the standard library to do the hard work for us.
> perf: use trailing and leading zeros in bitmath

- Cargo.toml
- src/entities/pool.rs
The tick value clamping in 'src/entities/pool.rs' has been refactored to use the built-in clamp method for more efficient and readable code. Additionally, the package version in 'Cargo.toml' has been updated from 0.28.0 to 0.29.0.
> chore: Refactor tick value clamping and bump package version

- Cargo.toml
- src/entities/mod.rs
- src/entities/pool.rs
- src/entities/position.rs
- src/entities/route.rs
- src/entities/tick.rs
- src/entities/tick_data_provider.rs
- src/entities/tick_list_data_provider.rs
- src/entities/trade.rs
- src/error.rs
- src/extensions/pool.rs
- src/lib.rs
- src/nonfungible_position_manager.rs
- src/quoter.rs
- src/staker.rs
- src/swap_router.rs
- src/tests.rs
- src/utils/encode_route_to_path.rs
- src/utils/nearest_usable_tick.rs
- src/utils/swap_math.rs
- src/utils/tick_list.rs
Adjusted the `Pool` and `Tick` structs and their methods to support generic index types, enhancing flexibility and type safety. This includes updating function signatures, trait bounds, and internal logic to utilize the new `TickIndex` trait, ensuring consistent behavior and eliminating the need for explicit integer types in tick operations.
> refactor: pool and tick handling for generic indices

- src/entities/pool.rs
Ensure the tick is recalculated if the square root price has changed, preventing incorrect behavior when moving to a new tick boundary. This addresses potential inconsistencies in state management during swaps.
> fix: recompute tick on price change in `Pool::_swap`

- Cargo.toml
- README.md
Updated various dependencies to their latest versions, including `alloy`, `uniswap-lens`, and `alloy-signer`, to maintain compatibility and improve functionality. Incremented the package version to reflect these updates.
> chore: upgrade dependencies and bump version to 2.9.0

- Cargo.toml
- README.md
Updated `uniswap-v3-sdk` to version 2.9.0 and upgraded dependencies: `alloy`, `alloy-signer`, and `uniswap-lens` to ensure compatibility with newer releases. Adjusted usage instructions in `README.md` to reflect new version.
> chore: bump package and dependency versions

- Cargo.toml
- README.md
Updated `uniswap-v3-sdk` to version 3.2.0 in Cargo.toml and README. Upgraded dependencies `alloy`, `uniswap-lens`, and others to their latest compatible versions. These changes ensure compatibility and take advantage of the latest improvements.
> chore: update dependencies and SDK version

- Cargo.toml
- examples/from_pool_key_with_tick_data_provider.rs
- examples/swap_router.rs
- src/extensions/state_overrides.rs
- src/self_permit.rs
Updated the crate version to 3.7.0 and upgraded dependencies like `alloy` and `uniswap-sdk-core`. Removed unnecessary references in method calls to align with updated function signatures. Minor code adjustments improve consistency and maintainability.
> chore: update dependencies and refactor method calls

- .github/workflows/rust.yml
- Cargo.toml
Upgraded `alloy`, `uniswap-lens`, and `tokio` dependencies to their latest versions for compatibility and improvements. Incremented package version to 3.7.1 to reflect these updates and maintain semantic versioning.
> chore: update dependencies and bump version to 3.7.1

- Cargo.toml
- README.md
- benches/swap_math.rs
- examples/from_pool_key_with_tick_data_provider.rs
- examples/nonfungible_position_manager.rs
- examples/self_permit.rs
- examples/swap_router.rs
- src/entities/trade.rs
- src/error.rs
- src/extensions/pool.rs
- src/extensions/position.rs
- src/extensions/price_tick_conversions.rs
- src/extensions/simple_tick_data_provider.rs
- src/extensions/state_overrides.rs
- src/multicall.rs
- src/nonfungible_position_manager.rs
- src/self_permit.rs
- src/tests.rs
Replaced deprecated `PrimitiveSignature` with `Signature` and updated method calls for improved validation and consistency. Upgraded several dependencies, including `alloy` and `uniswap-sdk-core`, and adjusted function signatures and API usage throughout the codebase to align with the new library versions. Incremented package version to `3.10.0`.
> refactor!: bump alloy to 1.0.1

- src/entities/pool.rs
- src/entities/position.rs
- src/error.rs
- src/utils/tick_math.rs
* refactor: improve error handling for liquidity overflow
Introduce `LiquidityOverflow` error for better handling of overflow scenarios in liquidity calculations. Add a corresponding test to ensure accurate error reporting.
* test: replace `should_panic` tests with precise error matching
Updated tests to use `assert!(matches!(...))` for specific error matching instead of `#[should_panic]` annotations. This improves clarity and ensures precise validation of error types and messages in failure scenarios.
* refactor: simplify error matching and make `Error` enum non-exhaustive
Updated tests to use `CoreError` alias for better readability in error matching. Added `#[non_exhaustive]` attribute to `Error` enum for forward compatibility.
> refactor: improve error handling for liquidity overflow
